name: flutter_transactions_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.2
  easy_localization: ^3.0.2
  easy_localization_loader: ^1.0.1+1
  flutter_bloc: ^8.1.3
  provider: ^6.0.5 
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^3.2.0
  sqflite: ^2.2.8+4
  syncfusion_flutter_charts: ^22.1.34


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/

